package: ytraduko
version: '0.1-dev'
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum/

requires:
    redaxo: '^5.3.0'

config:
    packages_ignore: [debug, tests, textile]
    packages_order:
        core_addons:
            - backup
            - be_style
            - cronjob
            - install
            - media_manager
            - mediapool
            - metainfo
            - phpmailer
            - project
            - structure
            - users
        y_addons:
            - ycom
            - yfeed
            - yform
            - yrewrite
            - ytraduko
